### ISSUE TITLE
pacdiff hook runs before reflector hook

### ISSUE THREAD

**Issue by skwerlman** [desbma/pacman-hooks#12]
since alpm hooks are run in alphabetical order, the pacdiff hook is run before the reflector hook.

this means that the full contents of the new default mirrorlist are printed to the console every time its updated, _and then_ the pacnew is renamed by the reflector hook so it doesnt show up in pacdiff runs.

an improved behavior would, imo, be running the reflector hook before pacdiff so the mirrorlist is not printed.

**Comment by desbma** [comment]
Good point, I have updated all the AUR packages to specify a relative order.
https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=reflector-pacman-hook-git&id=c20711c2bf3b7f5334bade647871e80685ed456b
https://aur.archlinux.org/cgit/aur.git/diff/PKGBUILD?h=pacdiff-pacman-hook-git&id=4c51380d60b484ac5865f0e5947eff2fb33aae84

**Comment by skwerlman** [comment]
nice, thank you!
