### ISSUE TITLE
Request: Check rpath

### ISSUE THREAD

**Issue by xiota** [desbma/pacman-hooks#16]
Checking rpath for intended library location could reduce false positives for some programs.

**Comment by desbma** [comment]
Do you have an example of such package?

**Comment by xiota** [comment]
`aur/localsend` uses `rpath`.  It installs to `/opt` by default, but can use `/usr/lib` by modifying a variable at beginning of the PKGBUILD.  When configured to use `/usr/lib`, this package does give false positive.  Other dart/flutter programs could be similar.

`aur/duckstation-git` also uses `rpath`.  It installs program and patched libraries to subdir of `/usr/lib`.  I have not tested, but it should give false positive, unless corresponding system library is installed (false negative).  At least one of the patched libraries has no corresponding system lib.

`pcsx2-git` uses `rpath`, but installs to `/opt`.  It uses patched libraries, similar to duckstation.

Probably many packages that currently install to `/opt` and include their own libraries use `rpath`, unless they set `LD_LIBRARY_PATH` in a script.

**Comment by desbma** [comment]
For `localsend` , it should be fixed by commit b45bb5581c587149b315eccfe6afa747ad0998e6, `check-broken-packages` now properly resolves symlinks before calling `ldd` so rpath/runpath is accounted for.

For the other packages you listed, `check-broken-packages` does not warn.
