### ISSUE TITLE
pacdiff.hook does not let me review anymore

### ISSUE THREAD

**Issue by Strykar** [desbma/pacman-hooks#2]
So the hook would let me review/delete pacnew files in the past, but now it just prints the options and exits to the prompt.

**Comment by desbma** [comment]
I don't know what you were using before, but it has always been non-interactive.

Unfortunately, pacman closes stdin before running runs hooks: https://git.archlinux.org/pacman.git/tree/lib/libalpm/util.c#n631 so there is currently no way to have hooks that interact with the parent shell.

**Comment by Strykar** [comment]
Thanks for clearing that up, if leaving me a bit confused, closing.  :)
