### ISSUE TITLE
[ENHANCEMENT] check-broken-packages auto rebuild?

### ISSUE THREAD

**Issue by kpa28-git** [desbma/pacman-hooks#6]
Hi.
I see that you have a check-broken-packages hook. I've been trying to write a hook that can check and rebuild AUR pacakges after a python update. The problem is pacman keeps the package db locked during the hook. Do you know of a way to workaround this somehow (maybe through scheduling the rebuild command after the pacman, yay, paur command ends)? I guess I could delete and re-add the lock, but that seems dangerous.

I'm not so experienced with pacman hooks. I've been looking for a workaround somehwere but haven't been able to find one. Know of a way to modify your or my hook to do this?

/etc/pacman.d/scripts/aur-python-rebuild:
```
#!/usr/bin/bash
# Find the AUR packages that require python and rebuild them

aur=$(pacman -Qqm | sort);
req=$(pactree -rl -d 1 "python" | sort);
sudo -u $SUDO_USER yay -S --answerclean=None --rebuild $(comm -12 <(echo "$aur") <(echo "$req"));
```

/etc/pacman.d/hooks/aur-python-rebuild.hook:
```
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = python

[Action]
Description = Rebuilding AUR packages that depend on python...
When = PostTransaction
Depends = coreutils
Depends = pacman
Depends = pacman-contrib
Depends = yay
Exec = /etc/pacman.d/scripts/aur-python-rebuild
```

**Comment by desbma** [comment]
I don't think having a hook that automatically rebuilds/installs packages is a desirable thing.
Package installation/upgrade is a sensitive operation, that may require keyboard input to make or confirm choice, which hooks do not allow.
Also there is clearly a recursion problem: building packages may install install packages which will trigger the hook, etc.

What I would do instead is maybe have a hook that writes packages to rebuild to a file for example in `/var/run/packages_to_rebuild`, and once your pacman/yay/whatever command has returned, use a script to run it again with packages from `/var/run/packages_to_rebuild`.

You could then have a shell function that runs both like that:
```
yay_autorebuild() {
    yay -Syu
    [ -f /var/run/packages_to_rebuild ] && cat /var/run/packages_to_rebuild | xargs -r yay --rebuild
}
```

**Comment by kpa28-git** [comment]
There wouldn't be a recursion problem. The hook is only triggered when python is installed / updated, not when other packages are. It only rebuilds AUR pacakges directly dependent on python.

New python dependent packages (that could trigger recursion) would be caught at the install phase, not at the hook. At the hook, the hook couldn't be triggered again anyway because you already have the latest version of python by virtue of the hook rebuilding these python dependent packages.

I agree about installing packages, but I don't think rebuilding exsitng pacakges is sensitive because I already installed them according to existing pkgbuilds.

Thank you for the suggestion. I get that it's easy to screw things up by modifying packages during a hook, it's probably for the best that pacman locks during hooks. As long as I have a way to automate this I'm happy.
