### ISSUE TITLE
unusual default shells break xmonad-recompile.hook

### ISSUE THREAD

**Issue by skwerlman** [desbma/pacman-hooks#9]
i recently switched to elvish as my default shell, and since doing that, the xmonad-recompile hook stopped working.

the reason is the call to `su -c` runs the command in the user's shell, but `<command> || true` is not valid elvish syntax, so it throws an error:
```
Multiple parse errors:
  should be form
    code from -c, line 1:
      xmonad --recompile || true
  unexpected rune '|'
    code from -c, line 1:
      xmonad --recompile || true
```

its possible to fix this by specifying a shell using the `-s` flag for `su`

my corrected Exec which specifies bash:
```
Exec=/usr/bin/bash -euc "command -v xmonad > /dev/null || exit 0; find /home -mindepth 1 -maxdepth 1 -type d -printf '%P\0' | xargs -0I'{}' su '{}' -s /usr/bin/bash -c 'xmonad --recompile || true '"
```

**Comment by desbma** [comment]
Thanks for the report, I have applied the fix you suggested.
